spring.application.name=demoinsforge
server.port=8080

# Conexion a PostgreSQL de InsForge
spring.datasource.url=jdbc:postgresql://rnmna87a.us-east.database.insforge.app:5432/insforge?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=6189539e8f6dd7cdaa3752bf67df4a5d
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuracion JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Pool de conexiones
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=20000

# Opcional: schema por defecto si lo necesitas
spring.jpa.properties.hibernate.default_schema=public