spring.application.name=productosapi
# Puerto del proyecto
server.port=8088

# Activar consola H2
spring.h2.console.enabled=true

# Ruta de la consola H2
spring.h2.console.path=/h2-console

# URL de la base de datos en memoria
spring.datasource.url=jdbc:h2:mem:productosdb

# Driver de H2
spring.datasource.driverClassName=org.h2.Driver

# Usuario por defecto
spring.datasource.username=sa

# Contraseña por defecto
spring.datasource.password=

# Crea la tabla automáticamente al iniciar
spring.jpa.hibernate.ddl-auto=create-drop

# Muestra SQL en consola
spring.jpa.show-sql=true