-- Creamos la tabla producto
CREATE TABLE producto (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          nombre VARCHAR(100) NOT NULL,
                          precio DOUBLE NOT NULL
);

-- Insertamos datos iniciales
INSERT INTO producto (nombre, precio) VALUES ('Teclado Gamer', 19990);
INSERT INTO producto (nombre, precio) VALUES ('Mouse Gamer', 9990);
INSERT INTO producto (nombre, precio) VALUES ('Audifonos USB', 24990);